<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="5.0.0-beta.2" />
    <PackageReference Include="Fable.Python" Version="4.*" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="chapters/01-introduction.fs" />
    <Compile Include="chapters/02-getting-started.fs" />
    <Compile Include="chapters/03-bindings.fs" />
    <Compile Include="chapters/04-compatibility.fs" />
  </ItemGroup>

</Project>
