(**
# Fable.Literate: The Strange Loop

You've made it to the end - and here's where things get delightfully meta.

**The blog post you're reading was generated by the code in this chapter.**

This is Fable.Literate, a literate programming converter inspired by
[jupytext](https://github.com/mwouts/jupytext) and
[FSharp.Formatting](https://fsprojects.github.io/FSharp.Formatting/).
It's written in F#, compiled to Python via Fable, and it processes the
`.fs` files that make up this blog - including itself.

The chain goes like this:

1. Each chapter is an F# file with embedded Markdown comments
2. Fable compiles the F# to Python
3. Fable.Literate (this code, running as Python) extracts the documentation
4. The output is the Markdown you're reading right now

It's a strange loop - the snake eating its tail. And it proves that
Fable.Python isn't just a toy: you're looking at a real project that works.

## How It Works

The converter follows a compiler-like architecture with three phases:

1. **Parse**: Convert source lines into a Block AST
2. **Transform**: Filter hidden blocks, resolve Python includes
3. **Print**: Render the AST as Markdown

The input syntax:

- Lines inside `(** ... *)` blocks become Markdown
- F# code outside those blocks is wrapped in fenced code blocks
- `(*** hide ***)` sections are excluded from output
- `(*** include-python: symbol1, symbol2 ***)` extracts generated Python code

*)

(*** hide ***)
open System
open Fable.Core
open Fable.Literate.Python

(**
## AST Types

The document is represented as a list of blocks. Each block represents
a distinct section of the literate source file:
*)

/// A single block in the document AST.
type Block =
    /// Raw markdown content from (** ... *) blocks
    | Markdown of content: string
    /// F# code that should be wrapped in fenced blocks
    | FSharpCode of lines: string list
    /// Hidden content - filtered out by Transform.filterHidden
    | Hidden of lines: string list
    /// Unresolved directive to include Python symbols (from parsing)
    /// Resolved to PythonCode by Transform.resolvePythonIncludes
    | IncludePython of symbols: string list
    /// Resolved Python code (after Transform.resolvePythonIncludes)
    | PythonCode of content: string

/// A parsed document is a list of blocks.
type Document = Block list

(**
## Utils Module

Utility functions for naming conversion and line classification:
*)

module Utils =
    /// List of contributors to thank (Fable-style).
    let contributors = [|
        "@dbrattli"
        "@alfonsogarciacaro"
        "@ncave"
        "@MangelMaxime"
        "@claude-code 🤖"
    |]

    /// Returns a random contributor from the list.
    let randomContributor () : string =
        let rnd = Random()
        contributors.[rnd.Next(contributors.Length)]

    /// Converts camelCase to snake_case for the function part.
    let private toSnakeCase (name: string) : string =
        if name.Length > 0 && Char.IsLower(name.[0]) then
            System.Text.RegularExpressions.Regex.Replace(
                name,
                "[a-z]?[A-Z]",
                fun m ->
                    if m.Value.Length = 1 then
                        m.Value.ToLowerInvariant()
                    else
                        m.Value.Substring(0, 1) + "_" + m.Value.Substring(1, 1).ToLowerInvariant()
            )
        else
            name

    /// Converts F# symbol reference to Python naming.
    /// - "Module.func" -> "Module_func" (Fable keeps camelCase for module functions)
    /// - "func" -> "func" (with snake_case conversion for top-level)
    let toPythonNaming (name: string) : string =
        match name.Split('.') with
        | [| moduleName; funcName |] -> moduleName + "_" + funcName // Module functions stay camelCase
        | _ -> toSnakeCase name // Top-level functions get snake_case

    /// Parses a comma-separated list of symbols from an include-python directive.
    let parseSymbolList (directive: string) : string list =
        // Extract content between "(*** include-python:" and "***)"
        let start = "(*** include-python:".Length
        let endPos = directive.LastIndexOf("***)")

        if endPos > start then
            directive.Substring(start, endPos - start).Trim()
            |> fun s -> s.Split(',')
            |> Array.map (fun s -> s.Trim())
            |> Array.filter (fun s -> s.Length > 0)
            |> Array.toList
        else
            []

    /// Active pattern for classifying source lines.
    /// - `HideCmd`: The (*** hide ***) directive
    /// - `IncludePythonCmd symbols`: The (*** include-python: sym1, sym2 ***) directive
    /// - `MarkdownSingle content`: Single-line markdown (** content *)
    /// - `MarkdownOpen content`: Start of markdown block, possibly with content
    /// - `MarkdownClose`: End of markdown block *)
    /// - `Content`: Any other line
    let (|HideCmd|IncludePythonCmd|MarkdownSingle|MarkdownOpen|MarkdownClose|Content|) (line: string) =
        let trimmed = line.Trim()

        match trimmed with
        | "(*** hide ***)" -> HideCmd
        | s when s.StartsWith("(*** include-python:") && s.EndsWith("***)") -> IncludePythonCmd(parseSymbolList s)
        | s when s.StartsWith("(**") && s.EndsWith("*)") && s.Length > 5 ->
            MarkdownSingle(s.Substring(3, s.Length - 5).Trim())
        | s when s.StartsWith("(**") ->
            let content = if s.Length > 3 then s.Substring(3).Trim() else ""
            MarkdownOpen content
        | "*)" -> MarkdownClose
        | _ -> Content

open Utils

(**
## Parser Module

The parser converts source lines into a Block AST using a fold:
*)

module Parser =
    /// Internal state for block accumulation during parsing.
    type private ParserState =
        | CollectingMarkdown of lines: string list
        | CollectingCode of lines: string list
        | CollectingHidden of lines: string list
        | Ready

    /// Parse context threaded through the fold.
    type private ParseContext = {
        State: ParserState
        Blocks: Block list // Accumulated blocks (in reverse)
    }

    /// Flush current state to a block if non-empty.
    let private flushState (ctx: ParseContext) : ParseContext =
        match ctx.State with
        | Ready -> ctx
        | CollectingMarkdown [] -> { ctx with State = Ready }
        | CollectingMarkdown lines ->
            let content = lines |> List.rev |> String.concat "\n"

            {
                State = Ready
                Blocks = Markdown content :: ctx.Blocks
            }
        | CollectingCode [] -> { ctx with State = Ready }
        | CollectingCode lines -> {
            State = Ready
            Blocks = FSharpCode(List.rev lines) :: ctx.Blocks
          }
        | CollectingHidden [] -> { ctx with State = Ready }
        | CollectingHidden lines -> {
            State = Ready
            Blocks = Hidden(List.rev lines) :: ctx.Blocks
          }

    /// Process a single line, updating parser state.
    let private parseLine (ctx: ParseContext) (line: string) : ParseContext =
        match ctx.State, line with
        // Hide directive - flush current, start hidden collection
        | _, HideCmd ->
            let flushed = flushState ctx
            { flushed with State = CollectingHidden [] }

        // Include-python directive - flush and emit as block
        | (CollectingCode _ | CollectingHidden _ | Ready), IncludePythonCmd symbols ->
            let flushed = flushState ctx
            { flushed with Blocks = IncludePython symbols :: flushed.Blocks }

        // Single-line markdown
        | (CollectingCode _ | CollectingHidden _ | Ready), MarkdownSingle content ->
            let flushed = flushState ctx
            { flushed with Blocks = Markdown content :: flushed.Blocks }

        // Start markdown block
        | (CollectingCode _ | CollectingHidden _ | Ready), MarkdownOpen content ->
            let flushed = flushState ctx
            let initial = if content.Length > 0 then [ content ] else []
            { flushed with State = CollectingMarkdown initial }

        // End markdown block
        | CollectingMarkdown _, MarkdownClose -> flushState ctx

        // Content in markdown
        | CollectingMarkdown lines, Content -> { ctx with State = CollectingMarkdown(line :: lines) }

        // Content in code mode
        | CollectingCode lines, Content -> { ctx with State = CollectingCode(line :: lines) }
        | Ready, Content -> { ctx with State = CollectingCode [ line ] }

        // Content in hidden mode
        | CollectingHidden lines, Content -> { ctx with State = CollectingHidden(line :: lines) }
        | CollectingHidden lines, MarkdownClose -> ctx // Stay hidden

        // Ignore invalid transitions
        | CollectingMarkdown _, (MarkdownOpen _ | MarkdownSingle _ | IncludePythonCmd _) -> ctx
        | (CollectingCode _ | Ready), MarkdownClose -> ctx

    /// Parse lines into a document AST.
    let parse (lines: string seq) : Document =
        let initial = {
            State = Ready
            Blocks = []
        }

        lines
        |> Seq.fold parseLine initial
        |> flushState
        |> fun ctx -> List.rev ctx.Blocks

(**
## Transform Module

Pure transformations on the document AST:
*)

module Transform =
    /// Boilerplate prefixes that should be excluded from code blocks.
    let boilerplatePrefixes = [ "module "; "namespace " ]

    /// Remove Hidden blocks from the document.
    let filterHidden (doc: Document) : Document =
        doc
        |> List.filter (function
            | Hidden _ -> false
            | _ -> true)

    /// Check if code lines are empty or boilerplate-only.
    let private isBoilerplate (lines: string list) : bool =
        let code = lines |> String.concat "\n" |> (fun s -> s.Trim())

        String.IsNullOrWhiteSpace code
        || boilerplatePrefixes |> List.exists (fun prefix -> code.Trim().StartsWith prefix)

    /// Remove empty or boilerplate-only code blocks.
    let filterBoilerplate (doc: Document) : Document =
        doc
        |> List.filter (function
            | FSharpCode lines when isBoilerplate lines -> false
            | _ -> true)

    /// Resolve IncludePython blocks to actual Python code blocks.
    let resolvePythonIncludes (pythonContent: string option) (doc: Document) : Document =
        doc
        |> List.map (function
            | IncludePython symbols ->
                let symbolList = String.concat ", " symbols

                match pythonContent with
                | Some content ->
                    let extracted = extractSymbols toPythonNaming symbols content

                    if String.IsNullOrWhiteSpace extracted then
                        Markdown $"<!-- include-python: {symbolList} (not found) -->"
                    else
                        PythonCode extracted
                | None -> Markdown $"<!-- include-python: {symbolList} (no --python-file) -->"
            | other -> other)

(**
## MarkdownPrinter Module

Renders the document AST to markdown:
*)

module MarkdownPrinter =
    /// Render a single block to markdown.
    let private printBlock (block: Block) : string =
        match block with
        | Markdown content -> content + "\n"
        | FSharpCode lines ->
            let code = lines |> String.concat "\n" |> (fun s -> s.Trim())
            "\n```fsharp\n" + code + "\n```\n\n"
        | PythonCode content -> "\n```python\n" + content + "\n```\n\n"
        | IncludePython symbols ->
            // Unresolved - should have been transformed
            let symbolList = String.concat ", " symbols
            "\n<!-- include-python: " + symbolList + " (unresolved) -->\n"
        | Hidden _ -> "" // Should have been filtered

    /// Render a document to markdown string.
    let printMarkdown (doc: Document) : string =
        doc |> List.map printBlock |> String.concat ""

    /// Increases all markdown header levels by one (# becomes ##, etc.).
    /// Preserves headers inside fenced code blocks.
    let adjustHeaderLevels (markdown: string) : string =
        let lines = markdown.Split('\n')

        let folder (inCodeBlock, acc) (line: string) =
            match line with
            | s when s.StartsWith "```" -> not inCodeBlock, line :: acc
            | _ when inCodeBlock -> inCodeBlock, line :: acc
            | s when s.StartsWith "#" -> inCodeBlock, ("#" + line) :: acc
            | _ -> inCodeBlock, line :: acc

        lines |> Array.fold folder (false, []) |> snd |> List.rev |> String.concat "\n"

(**
## Pipeline Module

Composes the phases into a complete pipeline:
*)

module Pipeline =
    /// Standard processing pipeline.
    let standard (pythonContent: string option) (lines: string seq) : string =
        lines
        |> Parser.parse
        |> Transform.filterHidden
        |> Transform.filterBoilerplate
        |> Transform.resolvePythonIncludes pythonContent
        |> MarkdownPrinter.printMarkdown

(**
## Including Generated Python Code

One of Fable.Literate's unique features is the ability to show the generated Python
alongside the F# source. The include-python directive extracts specific symbols
from the transpiled output.

When you pass `--python-file path` to Fable.Literate, it reads the transpiled
Python and extracts the named symbols (functions, classes, or variables).
This lets readers see exactly what Python code Fable generates from the F#.

The extraction is smart about Python syntax:

- It finds the symbol definition by matching patterns like def symbol or class symbol
- It walks backwards to include any decorators
- For multi-line definitions, it captures everything until the next top-level definition
- It stops before dunder methods to avoid pulling in too much

For example, the extractSymbol function in F# generates this Python:
*)

(*** include-python: extractSymbol ***)

(**
## Main Entry Point

Read the input file, convert it, and print the result:
*)

/// Gets the value following a flag argument (e.g., --python-file path.py).
let getFlagValue (flag: string) (args: string[]) : string option =
    // Find the index of the flag in args
    args
    |> Array.tryFindIndex ((=) flag)
    // Return the next argument if it exists
    |> Option.bind (fun i -> if i + 1 < args.Length then Some args.[i + 1] else None)

/// Extracts positional arguments (file paths) from command line args.
/// Filters out flags (--foo) and their values (--python-file path.py).
let getPositionalArgs (args: string[]) : string[] =
    let isFlag (arg: string) = arg.StartsWith "--"
    let isValueOfFlag i = i > 0 && args.[i - 1] = "--python-file"

    // Pair each argument with its index
    args
    |> Array.indexed
    // Keep only non-flags that aren't values of flags
    |> Array.filter (fun (i, arg) -> not (isFlag arg) && not (isValueOfFlag i))
    // Extract just the argument strings
    |> Array.map snd

/// Main entry point. Converts a literate F# file to Markdown.
/// Use --increase-headers flag to bump all header levels by one.
/// Use --python-file <path> to enable include-python directives.
[<EntryPoint>]
let main (args: string[]) =
    let hasFlag flag = args |> Array.contains flag
    let pythonFilePath = getFlagValue "--python-file" args
    let files = getPositionalArgs args

    if files.Length < 1 then
        printfn "Usage: python app.py [--increase-headers] [--python-file <path.py>] <input.fs>"
        1
    else
        // Thanks to the contributor! (Fable-style)
        eprintln $"Fable.Literate: Thanks to the contributor! {randomContributor ()}"

        // Load Python file content if provided
        let pythonContent = pythonFilePath |> Option.map readFile

        let content = readFile files.[0]
        let lines = content.Split('\n')

        // Pipeline: parse -> transform -> print
        let markdown = lines |> Pipeline.standard pythonContent

        let output =
            if hasFlag "--increase-headers" then
                MarkdownPrinter.adjustHeaderLevels markdown
            else
                markdown

        printRaw output
        0

(**
## Building and Running

```bash
# Transpile to Python
dotnet fable Fable.Literate/ --lang python -o output/Fable.Literate/

# Convert a literate file
python output/Fable.Literate/app.py chapters/introduction.fs > docs/introduction.md
```

That's it! A complete literate programming converter in under 200 lines of F#.

## The Punchline

If you're reading this, the code worked.

This entire blog post - every chapter, every code example, every explanation -
was processed by the F# code you just read, compiled to Python, and output
as Markdown. The proof is in the reading.

Welcome to Fable.Python. Now go build something.
*)
